version: "3.8"

networks:
  goapp-network:
    driver: bridge

services:
  postgres:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
      args:
        HOST_UID: ${HOST_UID:-70}
        HOST_GID: ${HOST_GID:-70}
    image: goapp-postgres
    container_name: goapp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goapp_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/var/postgres:/var/lib/postgresql/data/pgdata:rw
    ports:
      - "15432:5432"
    networks:
      - goapp-network
    restart: always
