version: "3.8"

networks:
  goapp-network:

services:

  app:
    image: goapp-app
    container_name: goapp-app
    build: 
      context: ./
      dockerfile: docker/app.Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    volumes:
      - ./:/app:rw
    depends_on:
      - postgres
    ports:
      - "7100:7100"
    networks:
      - goapp-network

  postgres:
    image: goapp-postgres
    container_name: goapp-postgres
    build:
      context: ./
      dockerfile: docker/postgres.Dockerfile
      args:
        HOST_UID: ${HOST_UID:-70}
        HOST_GID: ${HOST_GID:-70}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goapp_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/var/postgres:/var/lib/postgresql/data/pgdata:rw
    networks:
      - goapp-network
    restart: always
