# Env: development, production
app:
  Mode: development

rest:
  Listen: :7100
  MaxBodySize: 2M
  GzipLevel: 5
  ReadTimeout: 10
  WriteTimeout: 10
  ResponsePrettyEnabled: true
  ResponseStackEnabled: true

# Encoding:
# - json: ECS
# - text: ECS key-value pairs
# - pretty: readable for local development
logger:
  Encoding: pretty
  Level: debug

postgres:
  Host: localhost
  Port: 15432
  Dbname: goapp_db
  User: postgres
  Password: postgres
  SslMode: false
  MaxOpenConns: 5
  MaxIdleConns: 5
  ConnMaxLifetime: 300

