# Env: development, production
app:
  Mode: development

server:
  Listen: :7100
  MaxBodySize: 2M
  GzipLevel: 5
  ReadTimeout: 10
  WriteTimeout: 10

logger:
  Encoding: console
  Level: debug
  DevMode: false
  WithCaller: true
  WithStacktrace: true

postgres:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Dbname: boilerplate_db
  Sslmode: false
  Driver: pgx
